### ISSUE TITLE
Launch Volunteer Sign-up form

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#10]
**Background**
We have used multiple forms previously to sign-up volunteers for the Final Projects. It would be great to retire them and keep only a new one, if we think that is the right way to go

**Acceptance criteria**
- Identify all existent volunteer Final Project forms on our [drive](https://drive.google.com/drive/u/0/folders/0AJuBR443FU2FUk9PVA) + [Product Volunteers](https://docs.google.com/forms/d/10JLyTyfhriO-uuQCEjmMRzcwMz35P0f5i4tjKL2Ww70/edit) (this is a form Karen still uses for Tech Products, so we can rename it)
- Check out the [Class Planner](https://classplanner.codeyourfuture.io/) and understand if we can use it, instead of having a form 
- Define which information is needed (bare minimum, let's avoid GDPR)
- Create the final solution
- Update the documentation to onboard/explain process

**Comment by kfklein15** [comment]
Hi @RC-PM , how is this going? Would love to close this this week :)

**Comment by RC-PM** [comment]
I've finished incorporating the last changes to the generic one here: 
https://docs.google.com/forms/d/12knE1ZEToTHFs57xT470jkxhvuhm9gdPxYjWBBWVh4c/edit

Here's a version created for the two upcoming classes that asks for availability for both: 
https://docs.google.com/forms/d/1SAEXolw7aYAolhdiarAV4l7jaT0nylCXg32hQi1OTzg/edit

**Comment by kfklein15** [comment]
Looks great. Thank you!
