### ISSUE TITLE
Identifying interview availability

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#11]
**Background**
For Launch project we want volunteers to interview the trainees. In order to do this we need to have both sides availability. 

**Acceptance criteria**
- Process should be easy for both sides
- Define which platform or solution should we use
- Ideally no cost, but if there is a cost identify options so we can approve it
- Process must be mapped and documented
- Define next tickets if needed
- Update the documentation to onboard/explain process
- Do we need to use a spreadsheet for first iteration (25th May 2024 - if yes, what's the format)

**Comment by kfklein15** [comment]
@RC-PM , do you have an update on this?

**Comment by RC-PM** [comment]
To keep this light and free, I'm proposing we use a spreadsheet like this: https://docs.google.com/spreadsheets/d/1Gh33lsd6Xbs48eRYKkktASGX2gGfmLUq4zjB6d21fO8/edit#gid=1193594172

### Instructions for Students
So, you think you're ready to take on the Launch Module? Great! 

Before you jump in, we want to interview you and check whether you're ready to go right now or need a little more time to prepare. It's also a good chance to get some professional interview practice within a low stakes environment. 

**Task**: Book your interview

- Go to [this sheet](https://docs.google.com/spreadsheets/d/1Gh33lsd6Xbs48eRYKkktASGX2gGfmLUq4zjB6d21fO8/edit#gid=1193594172) 
- Look for an empty slot at a date and time that suits you 
- Add your name to **Candidate Name (on Slack)**, make sure it's the same as your Slack handle
- In a few days, you should receive a slack message confirming your interview time 
- You then need to add a reminder in your calendar for that day/time 
- On the day, you should be able to find the link to the interview on the [same sheet](https://docs.google.com/spreadsheets/d/1Gh33lsd6Xbs48eRYKkktASGX2gGfmLUq4zjB6d21fO8/edit#gid=1193594172) you entered your details)

### Instructions for Volunteers
Thanks for agreeing to help interview our Launch module candidates.

We just need to understand when you would be available to interview students. Sessions will be 30 minutes long, 25 minutes to chat and 5 minutes to writeup notes.

**Task**: Add interview availability

- Go to [this sheet](https://docs.google.com/spreadsheets/d/1Gh33lsd6Xbs48eRYKkktASGX2gGfmLUq4zjB6d21fO8/edit#gid=1193594172) 
- Review the Interviewer column, looking for Candidates with empty slots
- Whenever there is a slot you are certain you're available for 30 minutes, add your name
- If you have additional availability for empty slots without Candidates, please add that too
- In a few days, once we've confirmed times with the Candidates, we will message you on Slack to confirm. All the details should available and locked in the sheet
- On the day, you should be able to find the link to the interview on the [same sheet](https://docs.google.com/spreadsheets/d/1Gh33lsd6Xbs48eRYKkktASGX2gGfmLUq4zjB6d21fO8/edit#gid=1193594172) you entered your details

**Comment by RC-PM** [comment]
@kfklein15 Let me know what you think overall and I can finish off with any suggestions!

**Comment by kfklein15** [comment]
Looks ok for me - the multiple-tab one is maybe a bit complicated, but works. Let's test it :)

Can you add the instructions as a doc on the drive directly, @RC-PM , so we remember it, please?

**Comment by kfklein15** [comment]
Have you done this, @RC-PM ? If yes, please close this ticket.

**Comment by kfklein15** [comment]
Moved to our drive. https://docs.google.com/spreadsheets/d/1qOIt1Vm41w2MvsM3X19yUQc17oMCoh3KMnXu2ITbSUU/edit
