### ISSUE TITLE
Evidenced platform: understand it and define process

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#12]
**Background**
We use the platform [Evidenced](https://www.evidenced.app/) at CYF for our interviews. This ticket should be worked with @Barny-6 

**Acceptance criteria**
- Understand the platform and different roles
- Define a process to set-up volunteers
- Define process to set-up trainees
- Define process of booking the interviews 
- Update the documentation to onboard/explain process

**Comment by girdenis-p** [comment]
@kfklein15 @RC-PM I have made an [interview setup doc](https://docs.google.com/document/d/1VlHN4WqbMQTJyCXDGfBz-iu8EMEYvxKVcyRnEAw-oeA/edit). Let me know what you think. I have mentioned how the volunteers set themselves up, add trainees, and book the interview. Although the details of what the volunteers must do outside of Evidenced depends on #11.

**Comment by kfklein15** [comment]
Looks good. Only hiring managers can schedule interviews.
Let's refer to the Evidenced help section as much as possible.
https://help.evidenced.app/en/articles/8060809-managing-interviews

**Comment by girdenis-p** [comment]
@kfklein15 The [updated document](https://docs.google.com/document/d/1VlHN4WqbMQTJyCXDGfBz-iu8EMEYvxKVcyRnEAw-oeA/edit) now splits the roles of what the interviewers need to do (which is just to get invited to Evidenced and add themselves to available time slots on the interview slot spreadsheet) and what the hiring managers need to do (the arranging of interviews etc).

**Comment by kfklein15** [comment]
Looks good, @girdenis-p . Thanks for doing this.
