### ISSUE TITLE
Cover Letter Review Standard

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#15]
**Background**
Trainees will send us their Cover Letters, and we need to ensure that all volunteers review it with a standard lens.

**Acceptance criteria**
- Identify with the employability team (Barny) if we have a standard Cover Letter review document
- Review it to ensure it makes sense to Launch Module
- Make sure it is published somewhere easy to find
- Define the process of how we expect this to work (again, Barny can help with some input for this)
- Update the documentation to onboard/explain process

**Comment by girdenis-p** [comment]
@kfklein15, @RC-PM I did a bit of research on reviewing and writing cover letters and converted it into [a cover letter review standard](https://docs.google.com/document/d/1E5eHbbteQV2byb4b6C71ltiOKNj4eF0G4Kskz4YuVWY/edit?usp=sharing). I'd appreciate your feedback. Feel free to add any comments for clarity or to questions points.

**Comment by kfklein15** [comment]
Looks very good. I have tagged Barny on the document directly so he can give us his input.

**Comment by girdenis-p** [comment]
@kfklein15, I've added all of Barny's suggestions. We currently don't have any documentation pages on cover letters however (at least not in the Portfolio module).

**Comment by kfklein15** [comment]
@girdenis-p I have published the new criteria. I'm not sure where we are documenting this for the volunteers. 

https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv-1
