### ISSUE TITLE
Portfolio Review Standard

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#16]
**Background**
Trainees will send us their Portfolio, and we must ensure that all volunteers review it with a standard lens.

**Acceptance criteria**
- Identify with the employability team (Barny) if we have a standard Portfolio review document
- Review it to ensure it makes sense to Launch Module
- Make sure it is published somewhere easy to find
- Define the process of how we expect this to work (again, Barny can help with some input for this)
- Update the documentation to onboard/explain process

**Comment by girdenis-p** [comment]
Just as a note, the current portfolio standard is [on the Portfolio module](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/personal-website). [Barny mentioned on Slack](https://codeyourfuture.slack.com/archives/CCTV4D93K/p1711542946111779?thread_ts=1711454962.183539&cid=CCTV4D93K) that the guide is currently being worked on.

**Comment by kfklein15** [comment]
I have asked for the volunteers to give us access to their file so we can make suggestions and get a first draft - and update it on the Portfolio Module.

**Comment by kfklein15** [comment]
Portfolio doc has been published on our drive, not on Portfolio Module or Curriculum yet. But I will do this next sprint. 
https://docs.google.com/document/d/1rUyO6MAHYreENCOqQIW3MJDiRtc0K0Bz2jLj_b3Bzcc/edit

Not sure (again) where we are documenting this :D
