### ISSUE TITLE
Interview template on Evidenced

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#17]
**Background**
On Evidenced you can create a standard template for Launch Module. But we have some ready already, so we might be able to reuse them.

**Acceptance criteria**
- Check current templates of interviews on Evidenced
- Define which one to use or if a new one is needed
- Set the new one up and add it to the documentation process

**Comment by kfklein15** [comment]
These is my suggestions for the interview template. What do you think, @girdenis-p and @RC-PM 

1. Introduction (5 min)
1. Demo (10min)
1. Technical questions (15 min)
    - Ask questions related to the demo
    - 6 Optional questions you can choose 1/2 from, if needed, for example: 
                  - What is the biggest difficulty when working on this product?
                  - What would you have done if you had more time?
                  - What is docker?
1. Competency questions (15 min)
   - 13 questions you can choose 2-4 from (depending on time), for example:
                  - Tell me about a time you worked with a difficult person
                  - Tell me about a time you showed leadership.
1. Align expectations (5min)
    - Making sure they understand time commitment and their role 
1. Summary/Questions for candidates (5min)
   - Questions from candidates

**Comment by girdenis-p** [comment]
@kfklein15 the structure looks good to me. Will the questions themselves be decided at a later time?

**Comment by kfklein15** [comment]
No, they are on Evidenced already. I just can't copy and paste them easily.
