### ISSUE TITLE
Thank you e-mail - Trainees

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#28]
**Background**
After finishing the Module, we would like trainees know the next steps and their options

**Acceptance criteria**
- Create a thank you e-mail template with the following information
      - congratulating them for their hard work
      - explain Portfolio Module (which channels to go to)
      - searching for jobs (which channels to go to)
      - volunteering at CYF, with some examples such as Tech Products
- Define the process of how and when to send this
- Document the process
- Send the email

**Comment by girdenis-p** [comment]
[Thank you email draft](https://docs.google.com/document/d/1apK89THZ8WaqU_uqkOkdIj9G6ANuGhG7v2NMJcJ63gU/edit).

**Comment by girdenis-p** [comment]
@kfklein15 can you look at this and see if there are any other suggestions that should be added?

**Comment by kfklein15** [comment]
Should we send this email with their feedback?

**Comment by girdenis-p** [comment]
Yes we can do this, is there a general CYF email to send the emails from?

**Comment by kfklein15** [comment]
Use our Launch email - https://groups.google.com/a/codeyourfuture.io/g/launch-volunteers
