### ISSUE TITLE
Tech Lead Role: how much should they help

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#30]
what we expect of them?
let them fail?

**Comment by kfklein15** [comment]
@oliverlloyd , this is the Tech Lead description: https://docs.codeyourfuture.io/volunteers/teams-1/cyf-products-final-projects/roles/tech-lead

Could you please go through it and let me know which changes/addendum we should make to make things clearer? 
We can also spilt the role and make one ONLY for Tech Lead of the Launch Module if needed.

**Comment by oliverlloyd** [comment]
That list of responsibilities is already actually pretty great. The first one especially 

> Being part of the Product Team motivating team members and creating a space where they can ask questions and voice their concerns

This is excellent. It really brings to the fore the things that matter. Maybe we can give that more weight?

I would say that for Launch Projects specifically, there are areas where the expected role changes from what is already given. I've listed these below. I've then added some more that were not mentioned but which I think could be useful.

## Areas that might change between contexts
Looking at the list of responsibilities we have now, I would say these aspects might change in relation to Launch Module

### Architecture
Perhaps the role of tech lead for Launch Module could make it clear that the team own their solutions and it should be them writing all the code but that you are there to support them with suggested approaches when they get stuck

### Code reviews
The existing list of responsibilities mention `Doing quality code reviews that ensure the developers have appropriate feedback` but for LM I'm not sure if we want tech leads reviewing the team's PRs or not?

## Launch Project specific responsibilities
In addition, we could also include statements like these when defining the LM tech lead role:

- Help with breaking tasks down into tickets
- Take teams through the agile workflow: Assigning themselves to tickets, creating PRs, getting reviews, merging and deploying code
- Help teams with merge conflicts
- Make sure everyone is contributing
- You should not be writing or committing code but you can pair or mob with the students on tasks where they've got stuck to help unblock them
- Encourage teams to help each other as much as possible

**Comment by kfklein15** [comment]
Create new role. Make sure the details of this [architecture discussion](https://github.com/CodeYourFuture/launch_module_planning/issues/29) is included.

**Comment by kfklein15** [comment]
New role has been created and published. Thank you.
https://docs.codeyourfuture.io/volunteers/teams-1/cyf-products-final-projects/roles/tech-lead-1
