### ISSUE TITLE
Add Merge conflict workshop to Launch Module

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#31]
**Background**
A new workshop for Merge conflict has been created for the Launch Module.

**Acceptance criteria**
- Load the launch module workshop onto the first day of the Launch Modul

**Comment by girdenis-p** [comment]
[Link to the workshop](https://github.com/CodeYourFuture/CYF-Workshops/tree/main/dom-merge-conflict)

**Comment by kfklein15** [comment]
@SallyMcGrath said she added it to week 4 of DB Module, before Launch starts.
