### ISSUE TITLE
Communicate the kick-off dates on Slack

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#34]
**Background**
We need to ensure that everyone is clear about when the Launch Module will be. This can also help find volunteers internally.

**Acceptance criteria**
- Post on Launch channel
- Post on WM5 and NW6 channels
- Content should include: dates, process (interview, team allocation, reminder to apply, deadline to apply - WM5 this week, NW6 next week, etc)

**Comment by girdenis-p** [comment]
Links to messages:
[WM5 message](https://codeyourfuture.slack.com/archives/C05KCTSU67J/p1715778696510739)
[NW6 message](https://codeyourfuture.slack.com/archives/C05RPC3T4JH/p1715778719127869)
[Launch Project channel message](https://codeyourfuture.slack.com/archives/C0508C5EX71/p1715778649684689)
