### ISSUE TITLE
Identify availability for interview trainees

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#37]
**Background**
We need volunteers to interview trainees and to do that we need to identify everyone's availability

**Acceptance criteria**
- Check volunteers' availability for next week's interviews.
- We need 7 slots of 1 hour
      - Competency-based interviews: Addo (and Karen, if needed)
      - Technical interviews: Jay and Chris
- Ask the interviewers to access Evidenced and understand how it works
- Feedback must be written directly on Evidenced, using this [format](https://docs.google.com/document/d/1VQA9hM057DSVgWFXL2VEqM8alAXuRwQ7FNfx9eZPE2k/edit)

**Comment by girdenis-p** [comment]
[Volunteers have been asked](https://codeyourfuture.slack.com/archives/CCTV4D93K/p1717508025776409) to enter their availability for WM5 into [the spreadsheet for WM5](https://docs.google.com/spreadsheets/d/1h56MMnuHDHdrmeu04h_wrskGcIsmz65k4ta9NpiKzSQ/edit#gid=1606727102).

**Comment by girdenis-p** [comment]
[Volunteers have been asked](https://codeyourfuture.slack.com/archives/CCTV4D93K/p1718281690363309) to enter their availability for NW6 into [the corresponding spreadsheet](https://docs.google.com/spreadsheets/d/1C7Lpdn1B0HBbM71HYqtHpBJ0cw6MIDdVNDswjH2o8O4/edit?gid=0#gid=0).
