### ISSUE TITLE
Review trainees applications for WM5

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#38]
**Background**
Trainees apply to Launch Module with this form: https://docs.google.com/spreadsheets/d/1EoL7cWuqiWCNKh5jgB6_59g5h2w1ywvW5fkbJSwgy9s/edit?resourcekey#gid=863684053
We need to ensure they have good CV, cover letters and portfolios

**Acceptance criteria**
- Review CV using this [criteria](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv)
- Review cover letter using this [criteria](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv-1)
- Review Portfolio using this [criteria](https://docs.google.com/document/d/1rUyO6MAHYreENCOqQIW3MJDiRtc0K0Bz2jLj_b3Bzcc/edit)
- Send feedback to trainee

**Comment by kfklein15** [comment]
The trainees understood that all the mandatory/key work up till the application date should be done - which is fair enough, they can't finish work that isn't yet started. 

Volunteer will review these.

**Comment by kfklein15** [comment]
File to add feedback - we agreed to add it directly to the person's docs.
https://docs.google.com/spreadsheets/d/1CRWFHs__6-fBOYE6PEzWDf7UlczU-1RIez8vLZNR440/edit

**Comment by kfklein15** [comment]
This has been done for WM5 - as far as we can.
@girdenis-p , can you create a new ticket for the NW6 review, please?

**Comment by girdenis-p** [comment]
@kfklein15 I have created [the new ticket](https://github.com/CodeYourFuture/launch_module_planning/issues/56).
