### ISSUE TITLE
Review of trainees by volunteers

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#47]
**Background**
A final review should be given to the trainees about their performance in the team

**Acceptance criteria**
- PM and TL should write a review of every trainee using [this template](https://docs.google.com/document/d/1sgNNJNsgWprh7VMCbiRgXY1BrqjzqxdWKKxSvTZwcjk/edit?usp=drive_link)
- Trainees are not going to be considered course completers must be identified

**Comment by kfklein15** [comment]
Drive: https://drive.google.com/drive/u/0/folders/1B8qL1YP0ms9IxdVYUgdBVMfAGYutcsMs

**Comment by kfklein15** [comment]
Taiwo hasn't given feedback yet. @girdenis-p will follow up.

**Comment by girdenis-p** [comment]
Taiwo has written the tech feedback for his team. @kfklein15 would you be able to briefly look over and see if anything is missing in the all the reviews
