### ISSUE TITLE
Thank you e-mail to volunteers

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#49]
**Background**
We want to make sure the volunteers that supported us are being thanked

**Acceptance criteria**
- Create a thank you e-mail template with the following information
- congratulating them for their hard work
- explain Portfolio Module (which channels to go to)
- searching for jobs (which channels to go to)
- volunteering at CYF, with some examples
- Define the process of how and when to send this
- Document the process
- Send it to these volunteers
- Tell them about other opportunities and channels

**Comment by girdenis-p** [comment]
[Thank you email draft](https://docs.google.com/document/d/1dG8qQVaXd7O98hs2vqf4k_dHMAl5uONgSZ11ZK7GFuw/edit).

**Comment by kfklein15** [comment]
We made the changes together during the call.
