### ISSUE TITLE
Review trainee applications for NW6

### ISSUE THREAD

**Issue by girdenis-p** [CodeYourFuture/launch_module_planning#56]
**Background**
- We have [a spreadsheet of applications from NW6](https://docs.google.com/spreadsheets/d/1tCR8wZ2meJorisWAnkehgKo9GR_guJjX6iuhGRiZN6A/edit#gid=0). 
- We need to ensure the trainees have good CVs, cover letters and portfolios.

**Acceptance criteria**
- Review CV using this [criteria](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv).
- Review cover letter using this [criteria](https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv-1).
- Review portfolio using this [criteria](https://docs.google.com/document/d/1rUyO6MAHYreENCOqQIW3MJDiRtc0K0Bz2jLj_b3Bzcc/edit#heading=h.yxv6zfa0dw13).
- Give feedback by adding suggestions directly onto their CV and cover letter. Send portfolio feedback via email.

**Comment by kfklein15** [comment]
I have done two and sent feedback to candidates.

**Comment by girdenis-p** [comment]
I have done the remaining two and sent feedback to candidates
