### ISSUE TITLE
Post explaining Launch Module is a recurring module

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#60]
Launch Module: next Launch Project

**Comment by kfklein15** [comment]
@girdenis-p what do you think about the below post?

**Explanation about Launch Module**
I realised I didn't communicate the Launch Module as well as I could have, so hopefully this post will help. 

The Launch Module isn't linked to a specific cohort, which is how FInal Projects used to be. 

It usually happens as close as possible to the end of one, but it is run 4 times a year. The Launch Module happening in July/24 is the pilot of this new format.

The idea is that when people are ready, they can sign up for the next module and nail it - instead of being forced to do it and failing. 

So if you aren't in this module, make sure to go to [#cyf-launch-project](https://codeyourfuture.slack.com/archives/C0508C5EX71) and keep an eye for the next one.

If you still have questions, please add them to this thread so I can clarify anything.

**Comment by girdenis-p** [comment]
Yeah I think that should be fine to post in both the wm5 and nw6 channels

**Comment by kfklein15** [comment]
[WM5](https://codeyourfuture.slack.com/archives/C05KCTSU67J/p1720089762265339) and [NW6](https://codeyourfuture.slack.com/archives/C05RPC3T4JH/p1720089800898259)
