### ISSUE TITLE
Outreach for trainees

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#66]
**Background**
Trainees must sign-up for the Launch Module

**Acceptance criteria**
- Create a new form (or reuse an existing one?)
- Post on Slack on the Launch Module channel for people to sign up
- Share this post on the WM5 and NW6 channels

**Comment by girdenis-p** [comment]
I copied and created a new form in our protected drive. I have posted an announcement on the [Launch Module channel,](https://codeyourfuture.slack.com/archives/C0508C5EX71/p1722890641685449) [NW6 general channel](https://codeyourfuture.slack.com/archives/C05RPC3T4JH/p1722890681047269), and [WM5 announcements channel](https://codeyourfuture.slack.com/archives/C05L3722UFK/p1722890461020619).
