### ISSUE TITLE
Demo on 12th September (Thu)

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#79]
- Ensure all trainees on Launch Module Jul/24 can attend
- Invitation for all WM5 and NW6
- Expenses: covered for all trainees?
- Will we invite all WM grads (job seekers)?
- Will we invite NW grads (job seekers)?
Aim to invite everyone officially by the end of this week (2nd Aug)

**Comment by girdenis-p** [comment]
I have invited [NW](https://codeyourfuture.slack.com/archives/C5T03GZ7D/p1722593445732359) and [WM](https://codeyourfuture.slack.com/archives/C011ZSSTFQV/p1722593532212849) grads to register their interest in attending the external demos.

**Comment by kfklein15** [comment]
There is a meet-up event they can register directly: https://www.meetup.com/glasgow-and-birmingham-tech-for-good-by-code-your-future/events/302510281/

**Comment by kfklein15** [comment]
Have all trainees from WM and NW confirmed they will make it that day? The ones doing Launch at least.

**Comment by girdenis-p** [comment]
@kfklein15 4 / 5 have confirmed. Currently Fikret has not confirmed coming in person.
